### ISSUE TITLE
volla22 images

### ISSUE THREAD

**Issue by javiplx** [droidian-images/droidian#11]
Does https://github.com/droidian-images/droidian/commit/7fb6287cabd70956d4d5587b29627d88745ca882 means that volla22 is not supported? It's listed as official device, but details link is broken, and no image is found at github releases

**Comment by FakeShell** [comment]
vp22 is dropped for now. the port has to be rebased onto a newer version

**Comment by erikinkinen** [comment]
@javiplx , the reason for the drop is a bug which causes the Droidian installation to become corrupted when booted.

**Comment by Idcrafter** [comment]
also then drop cutie shell image which seems to also corrupt itself when rebooting

**Comment by FakeShell** [comment]
looks to also be dropped from cutie, we can close it for now until port gets revamped.

**Comment by javiplx** [comment]
I've seen a volla_mimameid-api30 on nightly build. Does it mean that the corruption bug is solved?

**Comment by erikinkinen** [comment]
@javiplx , yes, that is correct.
