### ISSUE TITLE
Samsung Galaxy Tab 4 (Android 4.4) support

### ISSUE THREAD

**Issue by anton2007** [droidian-images/droidian#2]
Hello!
I want to run Debian on my Samsung Galaxy Tab 4 (SM-T231), but looks like my Android API version is too low.
Is it possible to get Droidian on devices with API version lower than 28 like Galaxy Tab 4?

**Comment by mustafa-archived** [comment]
no

**Comment by mustafa-archived** [comment]
Altho depending on your model, you might be able to run debian (not droidian)

Do you have this one? https://wiki.postmarketos.org/wiki/Samsung_Galaxy_Tab_4_10.1_2015_(samsung-matisseve)

**Comment by erikinkinen** [comment]
Can I close this?

**Comment by mustafa-archived** [comment]
> Can I close this?

yeah just close it already
