### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by Korpyz** [droidian-images/droidian#6]
I need to take a guess. does this work like a gsi? I want to test it but I need to know if yes. I have a poco x3 pro and I know that its predecessor has an official version. I'm willing to unlock my device again just to test this wonder

**Comment by erikinkinen** [comment]
The generic images work almost like a gsi, but you will need to patch the kernel and may need to patch the rootfs slightly as well. If you have any further questions, you're also welcome to join our Telegram: https://t.me/DroidianLinux
